title: "Vyral Template"
# the subpath of your site, e.g. /blog
# baseurl: ""
baseurl: ""
# the base hostname & protocol for your site. Don't let it end in '/' or you'll mess the links up

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge

paginate: 6
permalink: none

collections:
    policies:
        output: true
        permalink: /:name
    custom_pages:
        output: true
        permalink: /:name

plugins:
    - jemoji
    - octopress-autoprefixer
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-admin
#  - jekyll-seo-tag

# Excludes
exclude:
    - .sass-cache
    - _site

sass:
    sass_dir: _sass

defaults:
    - scope:
          path: "" # an empty string here means all files in the project
      values:
          layout: "default"
    - scope:
          path: "" # an empty string here means all files in the project
          type: "posts" # limit to posts
      values:
          is_post: true # automatically set is_post=true for all posts
